import { useEffect, useState } from "react";
import { collection, query, where, orderBy, onSnapshot, addDoc, serverTimestamp, doc, setDoc } from "firebase/firestore";
import { db } from "../firebase";
import { useAuth } from "../context/AuthContext";
import { SearchIcon, SendIcon, MessageIcon } from "../components/Icons";

export default function Messages(){
 const {currentUser,profile}=useAuth(); const [users,setUsers]=useState([]); const [convos,setConvos]=useState([]); const [active,setActive]=useState(null); const [messages,setMessages]=useState([]); const [text,setText]=useState(""); const [search,setSearch]=useState("");
 useEffect(()=>onSnapshot(collection(db,"users"),s=>setUsers(s.docs.map(d=>({id:d.id,...d.data()})).filter(u=>u.id!==currentUser.uid))),[currentUser.uid]);
 useEffect(()=>onSnapshot(query(collection(db,"conversations"),where("participants","array-contains",currentUser.uid)),s=>setConvos(s.docs.map(d=>({id:d.id,...d.data()})))),[currentUser.uid]);
 useEffect(()=>{if(!active){setMessages([]);return;} return onSnapshot(query(collection(db,"conversations",active.id,"messages"),orderBy("createdAt","asc")),s=>setMessages(s.docs.map(d=>({id:d.id,...d.data()}))))},[active]);
 async function openUser(u){ const id=[currentUser.uid,u.id].sort().join("_"); await setDoc(doc(db,"conversations",id),{participants:[currentUser.uid,u.id],participantNames:{[currentUser.uid]:profile?.fullName||"Member",[u.id]:u.fullName||"Member"},updatedAt:serverTimestamp()},{merge:true}); setActive({id,other:u}); }
 async function send(e){e.preventDefault(); if(!text.trim()||!active)return; await addDoc(collection(db,"conversations",active.id,"messages"),{senderId:currentUser.uid,senderName:profile?.fullName||"Member",text:text.trim(),createdAt:serverTimestamp()}); await setDoc(doc(db,"conversations",active.id),{updatedAt:serverTimestamp(),lastMessage:text.trim(),lastSenderId:currentUser.uid},{merge:true}); setText(""); }
 const results=users.filter(u=>(u.fullName||"").toLowerCase().includes(search.toLowerCase()));
 return <div className="page messages-page"><div className="social-heading compact"><div><span className="eyebrow">Private conversations</span><h1>Messenger</h1></div><div className="heading-icon"><MessageIcon/></div></div><div className="messenger"><aside className="chat-sidebar"><div className="mini-search"><SearchIcon/><input placeholder="Find a member..." value={search} onChange={e=>setSearch(e.target.value)}/></div>{search&&results.map(u=><button className="chat-person" key={u.id} onClick={()=>openUser(u)}><Avatar name={u.fullName} photo={u.photoURL}/><span>{u.fullName}</span></button>)}{convos.map(c=>{const otherId=c.participants.find(id=>id!==currentUser.uid); const name=c.participantNames?.[otherId]||"Member"; return <button className={`chat-person ${active?.id===c.id?"selected":""}`} key={c.id} onClick={()=>openUser({id:otherId,fullName:name})}><span className="avatar-md avatar-placeholder">{name[0]}</span><span><b>{name}</b><small>{c.lastMessage||"Start a conversation"}</small></span></button>})}</aside><section className="chat-window">{active?<><header className="chat-header"><Avatar name={active.other.fullName} photo={active.other.photoURL}/><div><b>{active.other.fullName}</b><span>ChurchConnect member</span></div></header><div className="messages-list">{messages.map(m=><div key={m.id} className={`message-bubble ${m.senderId===currentUser.uid?"mine":""}`}>{m.text}</div>)}</div><form className="message-form" onSubmit={send}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message..."/><button className="btn-primary" type="submit"><SendIcon/> Send</button></form></>:<div className="empty-chat"><MessageIcon/><h3>Your messages</h3><p>Select a member or search for someone to start a conversation.</p></div>}</section></div></div>
}
function Avatar({name,photo}){return photo?<img className="avatar-md" src={photo} alt=""/>:<span className="avatar-md avatar-placeholder">{name?.[0]||"U"}</span>}
